project_id = "iukwizjteyfzljmizueb"

[functions.translate-product]
verify_jwt = false

[functions.send-financing-request]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.notify-shipping-cost]
verify_jwt = false

[functions.generate-invoice]
verify_jwt = false

[functions.detect-watermarks]
verify_jwt = false

[functions.scrape-product]
verify_jwt = false

[functions.scrape-category]
verify_jwt = false

[functions.generate-product-content]
verify_jwt = false

[functions.product-feed]
verify_jwt = false

[functions.chat]
verify_jwt = false
