import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { PDFDocument, rgb, StandardFonts } from "https://esm.sh/pdf-lib@1.17.1";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// Translations for invoice
const translations: Record<string, Record<string, string>> = {
  fr: {
    invoice: "FACTURE",
    invoiceNumber: "N°",
    date: "Date",
    status: "Statut",
    seller: "VENDEUR",
    billedTo: "FACTURÉ À",
    description: "Description",
    qty: "Qté",
    unitPrice: "Prix unit.",
    total: "Total",
    subtotalHT: "Sous-total HT",
    vat: "TVA (20%)",
    totalTTC: "TOTAL TTC",
    paymentInfo: "Informations de paiement",
    paymentMethod: "Mode de paiement: Virement bancaire",
    reference: "Référence",
    marketplace: "Marketplace de Matériel Agricole",
    autoGenerated: "Document généré automatiquement - Facture valide sans signature",
    pending: "En attente",
    confirmed: "Confirmée",
    shipped: "Expédiée",
    delivered: "Livrée",
    cancelled: "Annulée",
    paid: "Payée",
  },
  en: {
    invoice: "INVOICE",
    invoiceNumber: "No.",
    date: "Date",
    status: "Status",
    seller: "SELLER",
    billedTo: "BILLED TO",
    description: "Description",
    qty: "Qty",
    unitPrice: "Unit price",
    total: "Total",
    subtotalHT: "Subtotal excl. VAT",
    vat: "VAT (20%)",
    totalTTC: "TOTAL incl. VAT",
    paymentInfo: "Payment information",
    paymentMethod: "Payment method: Bank transfer",
    reference: "Reference",
    marketplace: "Agricultural Equipment Marketplace",
    autoGenerated: "Automatically generated document - Valid invoice without signature",
    pending: "Pending",
    confirmed: "Confirmed",
    shipped: "Shipped",
    delivered: "Delivered",
    cancelled: "Cancelled",
    paid: "Paid",
  },
  de: {
    invoice: "RECHNUNG",
    invoiceNumber: "Nr.",
    date: "Datum",
    status: "Status",
    seller: "VERKÄUFER",
    billedTo: "RECHNUNGSADRESSE",
    description: "Beschreibung",
    qty: "Menge",
    unitPrice: "Einzelpreis",
    total: "Gesamt",
    subtotalHT: "Zwischensumme netto",
    vat: "MwSt. (20%)",
    totalTTC: "GESAMTBETRAG brutto",
    paymentInfo: "Zahlungsinformationen",
    paymentMethod: "Zahlungsart: Banküberweisung",
    reference: "Referenz",
    marketplace: "Marktplatz für Landmaschinen",
    autoGenerated: "Automatisch generiertes Dokument - Gültige Rechnung ohne Unterschrift",
    pending: "Ausstehend",
    confirmed: "Bestätigt",
    shipped: "Versendet",
    delivered: "Geliefert",
    cancelled: "Storniert",
    paid: "Bezahlt",
  },
  es: {
    invoice: "FACTURA",
    invoiceNumber: "N°",
    date: "Fecha",
    status: "Estado",
    seller: "VENDEDOR",
    billedTo: "FACTURAR A",
    description: "Descripción",
    qty: "Cant.",
    unitPrice: "Precio unit.",
    total: "Total",
    subtotalHT: "Subtotal sin IVA",
    vat: "IVA (20%)",
    totalTTC: "TOTAL con IVA",
    paymentInfo: "Información de pago",
    paymentMethod: "Método de pago: Transferencia bancaria",
    reference: "Referencia",
    marketplace: "Marketplace de Maquinaria Agrícola",
    autoGenerated: "Documento generado automáticamente - Factura válida sin firma",
    pending: "Pendiente",
    confirmed: "Confirmada",
    shipped: "Enviada",
    delivered: "Entregada",
    cancelled: "Cancelada",
    paid: "Pagada",
  },
  it: {
    invoice: "FATTURA",
    invoiceNumber: "N°",
    date: "Data",
    status: "Stato",
    seller: "VENDITORE",
    billedTo: "FATTURARE A",
    description: "Descrizione",
    qty: "Qtà",
    unitPrice: "Prezzo unit.",
    total: "Totale",
    subtotalHT: "Subtotale esclusa IVA",
    vat: "IVA (20%)",
    totalTTC: "TOTALE IVA inclusa",
    paymentInfo: "Informazioni di pagamento",
    paymentMethod: "Metodo di pagamento: Bonifico bancario",
    reference: "Riferimento",
    marketplace: "Marketplace di Macchine Agricole",
    autoGenerated: "Documento generato automaticamente - Fattura valida senza firma",
    pending: "In attesa",
    confirmed: "Confermata",
    shipped: "Spedita",
    delivered: "Consegnata",
    cancelled: "Annullata",
    paid: "Pagata",
  },
  pt: {
    invoice: "FATURA",
    invoiceNumber: "N°",
    date: "Data",
    status: "Estado",
    seller: "VENDEDOR",
    billedTo: "FATURAR PARA",
    description: "Descrição",
    qty: "Qtd.",
    unitPrice: "Preço unit.",
    total: "Total",
    subtotalHT: "Subtotal sem IVA",
    vat: "IVA (20%)",
    totalTTC: "TOTAL com IVA",
    paymentInfo: "Informações de pagamento",
    paymentMethod: "Método de pagamento: Transferência bancária",
    reference: "Referência",
    marketplace: "Marketplace de Máquinas Agrícolas",
    autoGenerated: "Documento gerado automaticamente - Fatura válida sem assinatura",
    pending: "Pendente",
    confirmed: "Confirmada",
    shipped: "Enviada",
    delivered: "Entregue",
    cancelled: "Cancelada",
    paid: "Paga",
  },
};

function getLocale(lang: string): string {
  const locales: Record<string, string> = {
    fr: "fr-FR",
    en: "en-GB",
    de: "de-DE",
    es: "es-ES",
    it: "it-IT",
    pt: "pt-PT",
  };
  return locales[lang] || "fr-FR";
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
    );

    const { orderId, language = "fr" } = await req.json();
    const lang = translations[language] ? language : "fr";
    const t = translations[lang];
    const locale = getLocale(lang);

    if (!orderId) {
      return new Response(
        JSON.stringify({ error: "Order ID is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Fetch order
    const { data: order, error: orderError } = await supabaseClient
      .from("orders")
      .select("*")
      .eq("id", orderId)
      .single();

    if (orderError || !order) {
      console.error("Order fetch error:", orderError);
      return new Response(
        JSON.stringify({ error: "Order not found" }),
        { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Fetch order items
    const { data: orderItems, error: itemsError } = await supabaseClient
      .from("order_items")
      .select("*")
      .eq("order_id", orderId);

    if (itemsError) {
      console.error("Order items fetch error:", itemsError);
      return new Response(
        JSON.stringify({ error: "Failed to fetch order items" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Fetch bank accounts from database
    const { data: bankAccounts } = await supabaseClient
      .from("bank_accounts")
      .select("*")
      .eq("is_active", true);

    // Generate invoice number and date
    const invoiceNumber = `INV-${new Date(order.created_at).getFullYear()}-${order.id.slice(0, 8).toUpperCase()}`;
    const invoiceDate = new Date(order.created_at).toLocaleDateString(locale);

    // Create PDF document
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([595, 842]); // A4 size in points
    const { width, height } = page.getSize();

    // Embed fonts
    const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica);

    // Colors
    const primaryColor = rgb(0.18, 0.35, 0.15);
    const accentColor = rgb(0.96, 0.62, 0.04);
    const textColor = rgb(0.2, 0.2, 0.2);
    const mutedColor = rgb(0.4, 0.4, 0.4);

    let yPos = height - 50;

    // Header - Logo
    page.drawText("Equip", {
      x: 50,
      y: yPos,
      size: 28,
      font: helveticaBold,
      color: primaryColor,
    });
    page.drawText("Trade", {
      x: 50 + helveticaBold.widthOfTextAtSize("Equip", 28),
      y: yPos,
      size: 28,
      font: helveticaBold,
      color: accentColor,
    });

    // Header - Invoice info (right side)
    page.drawText(t.invoice, {
      x: width - 150,
      y: yPos,
      size: 24,
      font: helveticaBold,
      color: primaryColor,
    });

    yPos -= 25;
    page.drawText(`${t.invoiceNumber}: ${invoiceNumber}`, {
      x: width - 150,
      y: yPos,
      size: 10,
      font: helvetica,
      color: mutedColor,
    });

    yPos -= 15;
    page.drawText(`${t.date}: ${invoiceDate}`, {
      x: width - 150,
      y: yPos,
      size: 10,
      font: helvetica,
      color: mutedColor,
    });

    yPos -= 15;
    const statusLabel = t[order.status as keyof typeof t] || order.status;
    page.drawText(`${t.status}: ${statusLabel}`, {
      x: width - 150,
      y: yPos,
      size: 10,
      font: helvetica,
      color: mutedColor,
    });

    // Header line
    yPos -= 20;
    page.drawLine({
      start: { x: 50, y: yPos },
      end: { x: width - 50, y: yPos },
      thickness: 2,
      color: primaryColor,
    });

    // Addresses section
    yPos -= 40;

    // Seller address
    page.drawText(t.seller, {
      x: 50,
      y: yPos,
      size: 10,
      font: helveticaBold,
      color: primaryColor,
    });
    yPos -= 18;
    page.drawText("EquipTrade", { x: 50, y: yPos, size: 11, font: helveticaBold, color: textColor });
    yPos -= 15;
    page.drawText(t.marketplace, { x: 50, y: yPos, size: 10, font: helvetica, color: mutedColor });
    yPos -= 15;
    page.drawText("France", { x: 50, y: yPos, size: 10, font: helvetica, color: mutedColor });
    yPos -= 15;
    page.drawText("contact@equiptrade.fr", { x: 50, y: yPos, size: 10, font: helvetica, color: mutedColor });

    // Client address (right side)
    let clientY = yPos + 63;
    page.drawText(t.billedTo, {
      x: 320,
      y: clientY,
      size: 10,
      font: helveticaBold,
      color: primaryColor,
    });
    clientY -= 18;
    page.drawText(order.shipping_name || "N/A", { x: 320, y: clientY, size: 11, font: helveticaBold, color: textColor });
    clientY -= 15;
    if (order.shipping_address) {
      page.drawText(order.shipping_address, { x: 320, y: clientY, size: 10, font: helvetica, color: mutedColor });
      clientY -= 15;
    }
    page.drawText(`${order.shipping_postal_code || ""} ${order.shipping_city || ""}`.trim(), { x: 320, y: clientY, size: 10, font: helvetica, color: mutedColor });
    clientY -= 15;
    page.drawText(order.shipping_country || "France", { x: 320, y: clientY, size: 10, font: helvetica, color: mutedColor });
    clientY -= 15;
    if (order.shipping_email) {
      page.drawText(order.shipping_email, { x: 320, y: clientY, size: 10, font: helvetica, color: mutedColor });
      clientY -= 15;
    }
    if (order.shipping_phone) {
      page.drawText(order.shipping_phone, { x: 320, y: clientY, size: 10, font: helvetica, color: mutedColor });
    }

    // Items table
    yPos -= 60;

    // Table header
    page.drawRectangle({
      x: 50,
      y: yPos - 5,
      width: width - 100,
      height: 25,
      color: primaryColor,
    });

    page.drawText(t.description, { x: 55, y: yPos + 3, size: 10, font: helveticaBold, color: rgb(1, 1, 1) });
    page.drawText(t.qty, { x: 340, y: yPos + 3, size: 10, font: helveticaBold, color: rgb(1, 1, 1) });
    page.drawText(t.unitPrice, { x: 390, y: yPos + 3, size: 10, font: helveticaBold, color: rgb(1, 1, 1) });
    page.drawText(t.total, { x: 480, y: yPos + 3, size: 10, font: helveticaBold, color: rgb(1, 1, 1) });

    yPos -= 25;

    // Table rows
    let subtotalHT = 0;
    for (let i = 0; i < (orderItems?.length || 0); i++) {
      const item = orderItems![i];
      const itemTotal = item.product_price * item.quantity;
      subtotalHT += itemTotal;

      // Alternate row background
      if (i % 2 === 1) {
        page.drawRectangle({
          x: 50,
          y: yPos - 5,
          width: width - 100,
          height: 22,
          color: rgb(0.97, 0.97, 0.97),
        });
      }

      // Truncate long titles
      let title = item.product_title;
      if (title.length > 40) {
        title = title.substring(0, 37) + "...";
      }

      page.drawText(title, { x: 55, y: yPos + 3, size: 10, font: helvetica, color: textColor });
      page.drawText(item.quantity.toString(), { x: 350, y: yPos + 3, size: 10, font: helvetica, color: textColor });
      page.drawText(formatPrice(item.product_price, locale), { x: 390, y: yPos + 3, size: 10, font: helvetica, color: textColor });
      page.drawText(formatPrice(itemTotal, locale), { x: 480, y: yPos + 3, size: 10, font: helvetica, color: textColor });

      yPos -= 22;
    }

    // Separator line
    yPos -= 10;
    page.drawLine({
      start: { x: 50, y: yPos },
      end: { x: width - 50, y: yPos },
      thickness: 0.5,
      color: rgb(0.85, 0.85, 0.85),
    });

    // Totals section (right aligned)
    yPos -= 30;
    const totalsX = 380;

    // Calculate HT and TVA
    const htAmount = subtotalHT / 1.20;
    const tvaAmount = subtotalHT - htAmount;

    page.drawText(`${t.subtotalHT}:`, { x: totalsX, y: yPos, size: 10, font: helvetica, color: mutedColor });
    page.drawText(formatPrice(htAmount, locale), { x: 480, y: yPos, size: 10, font: helvetica, color: textColor });

    yPos -= 18;
    page.drawText(`${t.vat}:`, { x: totalsX, y: yPos, size: 10, font: helvetica, color: mutedColor });
    page.drawText(formatPrice(tvaAmount, locale), { x: 480, y: yPos, size: 10, font: helvetica, color: textColor });

    yPos -= 25;
    // Total TTC box
    page.drawRectangle({
      x: totalsX - 10,
      y: yPos - 8,
      width: width - totalsX - 30,
      height: 28,
      color: primaryColor,
    });
    page.drawText(`${t.totalTTC}:`, { x: totalsX, y: yPos, size: 12, font: helveticaBold, color: rgb(1, 1, 1) });
    page.drawText(formatPrice(subtotalHT, locale), { x: 475, y: yPos, size: 12, font: helveticaBold, color: rgb(1, 1, 1) });

    // Bank info section
    yPos -= 60;
    page.drawRectangle({
      x: 50,
      y: yPos - 80,
      width: width - 100,
      height: 95,
      color: rgb(0.97, 0.97, 0.97),
      borderColor: rgb(0.9, 0.9, 0.9),
      borderWidth: 1,
    });

    page.drawText(t.paymentInfo, { x: 60, y: yPos - 15, size: 12, font: helveticaBold, color: primaryColor });
    page.drawText(t.paymentMethod, { x: 60, y: yPos - 35, size: 10, font: helvetica, color: mutedColor });
    
    // Get bank details from database or use defaults
    let bankDetails = { iban: "FR76 1234 5678 9012 3456 7890 123", bic: "AGRIFRPP" };
    if (bankAccounts && bankAccounts.length > 0) {
      const selectedAccount = bankAccounts.find(acc => 
        order.total_amount >= (acc.threshold_min || 0) && 
        (acc.threshold_max === null || order.total_amount <= acc.threshold_max)
      ) || bankAccounts[0];
      bankDetails = { iban: selectedAccount.iban, bic: selectedAccount.bic };
    } else if (order.total_amount >= 5000) {
      bankDetails = { iban: "FR76 9876 5432 1098 7654 3210 987", bic: "BNPAFRPP" };
    }
    
    page.drawText(`IBAN: ${bankDetails.iban}`, { x: 60, y: yPos - 50, size: 10, font: helvetica, color: mutedColor });
    page.drawText(`BIC: ${bankDetails.bic}`, { x: 60, y: yPos - 65, size: 10, font: helvetica, color: mutedColor });
    page.drawText(`${t.reference}: ${invoiceNumber}`, { x: 350, y: yPos - 50, size: 10, font: helvetica, color: mutedColor });

    // Footer
    const footerY = 50;
    page.drawLine({
      start: { x: 50, y: footerY + 20 },
      end: { x: width - 50, y: footerY + 20 },
      thickness: 0.5,
      color: rgb(0.85, 0.85, 0.85),
    });

    page.drawText(`EquipTrade - ${t.marketplace}`, {
      x: 180,
      y: footerY + 5,
      size: 9,
      font: helvetica,
      color: mutedColor,
    });
    page.drawText(t.autoGenerated, {
      x: 120,
      y: footerY - 10,
      size: 8,
      font: helvetica,
      color: rgb(0.6, 0.6, 0.6),
    });

    // Serialize PDF to bytes
    const pdfBytes = await pdfDoc.save();

    return new Response(new Uint8Array(pdfBytes).buffer as ArrayBuffer, {
      headers: {
        ...corsHeaders,
        "Content-Type": "application/pdf",
        "Content-Disposition": `inline; filename="facture-${invoiceNumber}.pdf"`,
      },
    });
  } catch (error: unknown) {
    console.error("Error generating invoice:", error);
    const errorMessage = error instanceof Error ? error.message : "Unknown error";
    return new Response(
      JSON.stringify({ error: "Failed to generate invoice", details: errorMessage }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});

function formatPrice(price: number, locale: string): string {
  return new Intl.NumberFormat(locale, {
    style: "currency",
    currency: "EUR",
  }).format(price);
}
