import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { PDFDocument, rgb, StandardFonts } from "https://esm.sh/pdf-lib@1.17.1";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// Translations for invoice - all unified per language
const translations: Record<string, Record<string, string>> = {
  fr: {
    invoice: "FACTURE",
    invoiceNumber: "No",
    date: "Date",
    status: "Statut",
    seller: "VENDEUR",
    billedTo: "FACTURE A",
    description: "Description",
    qty: "Qte",
    unitPrice: "Prix unit.",
    total: "Total",
    subtotalHT: "Sous-total HT",
    vat: "TVA (20%)",
    totalTTC: "TOTAL TTC",
    paymentInfo: "Informations de paiement",
    paymentMethod: "Mode de paiement: Virement bancaire",
    reference: "Reference",
    marketplace: "Equipement Agricole Neuf et Occasion",
    autoGenerated: "Document genere automatiquement - Facture valide sans signature",
    pending: "En attente",
    payment_uploaded: "Paiement a verifier",
    confirmed: "Confirmee",
    shipped: "Expediee",
    delivered: "Livree",
    cancelled: "Annulee",
    paid: "Payee",
    companyReg: "Enregistrement: ",
    vatNumber: "No TVA: ",
    termsTitle: "Conditions",
    terms: "Paiement a reception. Retards soumis a interets.",
    bankDetails: "Coordonnees bancaires",
  },
  en: {
    invoice: "INVOICE",
    invoiceNumber: "No.",
    date: "Date",
    status: "Status",
    seller: "SELLER",
    billedTo: "BILLED TO",
    description: "Description",
    qty: "Qty",
    unitPrice: "Unit price",
    total: "Total",
    subtotalHT: "Subtotal excl. VAT",
    vat: "VAT (20%)",
    totalTTC: "TOTAL incl. VAT",
    paymentInfo: "Payment information",
    paymentMethod: "Payment method: Bank transfer",
    reference: "Reference",
    marketplace: "New and Used Agricultural Equipment",
    autoGenerated: "Automatically generated document - Valid invoice without signature",
    pending: "Pending",
    payment_uploaded: "Payment to verify",
    confirmed: "Confirmed",
    shipped: "Shipped",
    delivered: "Delivered",
    cancelled: "Cancelled",
    paid: "Paid",
    companyReg: "Company No: ",
    vatNumber: "VAT No: ",
    termsTitle: "Terms",
    terms: "Payment due on receipt. Late payments subject to interest.",
    bankDetails: "Bank details",
  },
  de: {
    invoice: "RECHNUNG",
    invoiceNumber: "Nr.",
    date: "Datum",
    status: "Status",
    seller: "VERKAUFER",
    billedTo: "RECHNUNGSADRESSE",
    description: "Beschreibung",
    qty: "Menge",
    unitPrice: "Einzelpreis",
    total: "Gesamt",
    subtotalHT: "Zwischensumme netto",
    vat: "MwSt. (20%)",
    totalTTC: "GESAMTBETRAG brutto",
    paymentInfo: "Zahlungsinformationen",
    paymentMethod: "Zahlungsart: Bankuberweisung",
    reference: "Referenz",
    marketplace: "Neue und Gebrauchte Landmaschinen",
    autoGenerated: "Automatisch generiertes Dokument - Gultige Rechnung ohne Unterschrift",
    pending: "Ausstehend",
    payment_uploaded: "Zahlung zu prufen",
    confirmed: "Bestatigt",
    shipped: "Versendet",
    delivered: "Geliefert",
    cancelled: "Storniert",
    paid: "Bezahlt",
    companyReg: "Handelsregister: ",
    vatNumber: "USt-IdNr: ",
    termsTitle: "Bedingungen",
    terms: "Zahlung bei Erhalt. Verzugszinsen bei verspateter Zahlung.",
    bankDetails: "Bankverbindung",
  },
  es: {
    invoice: "FACTURA",
    invoiceNumber: "No",
    date: "Fecha",
    status: "Estado",
    seller: "VENDEDOR",
    billedTo: "FACTURAR A",
    description: "Descripcion",
    qty: "Cant.",
    unitPrice: "Precio unit.",
    total: "Total",
    subtotalHT: "Subtotal sin IVA",
    vat: "IVA (20%)",
    totalTTC: "TOTAL con IVA",
    paymentInfo: "Informacion de pago",
    paymentMethod: "Metodo de pago: Transferencia bancaria",
    reference: "Referencia",
    marketplace: "Maquinaria Agricola Nueva y Usada",
    autoGenerated: "Documento generado automaticamente - Factura valida sin firma",
    pending: "Pendiente",
    payment_uploaded: "Pago a verificar",
    confirmed: "Confirmada",
    shipped: "Enviada",
    delivered: "Entregada",
    cancelled: "Cancelada",
    paid: "Pagada",
    companyReg: "Registro: ",
    vatNumber: "No IVA: ",
    termsTitle: "Condiciones",
    terms: "Pago al recibo. Pagos atrasados sujetos a intereses.",
    bankDetails: "Datos bancarios",
  },
  it: {
    invoice: "FATTURA",
    invoiceNumber: "No",
    date: "Data",
    status: "Stato",
    seller: "VENDITORE",
    billedTo: "FATTURARE A",
    description: "Descrizione",
    qty: "Qta",
    unitPrice: "Prezzo unit.",
    total: "Totale",
    subtotalHT: "Subtotale esclusa IVA",
    vat: "IVA (20%)",
    totalTTC: "TOTALE IVA inclusa",
    paymentInfo: "Informazioni di pagamento",
    paymentMethod: "Metodo di pagamento: Bonifico bancario",
    reference: "Riferimento",
    marketplace: "Macchine Agricole Nuove e Usate",
    autoGenerated: "Documento generato automaticamente - Fattura valida senza firma",
    pending: "In attesa",
    payment_uploaded: "Pagamento da verificare",
    confirmed: "Confermata",
    shipped: "Spedita",
    delivered: "Consegnata",
    cancelled: "Annullata",
    paid: "Pagata",
    companyReg: "Registro: ",
    vatNumber: "P.IVA: ",
    termsTitle: "Condizioni",
    terms: "Pagamento alla ricezione. Ritardi soggetti a interessi.",
    bankDetails: "Coordinate bancarie",
  },
  pt: {
    invoice: "FATURA",
    invoiceNumber: "No",
    date: "Data",
    status: "Estado",
    seller: "VENDEDOR",
    billedTo: "FATURAR PARA",
    description: "Descricao",
    qty: "Qtd.",
    unitPrice: "Preco unit.",
    total: "Total",
    subtotalHT: "Subtotal sem IVA",
    vat: "IVA (20%)",
    totalTTC: "TOTAL com IVA",
    paymentInfo: "Informacoes de pagamento",
    paymentMethod: "Metodo de pagamento: Transferencia bancaria",
    reference: "Referencia",
    marketplace: "Maquinas Agricolas Novas e Usadas",
    autoGenerated: "Documento gerado automaticamente - Fatura valida sem assinatura",
    pending: "Pendente",
    payment_uploaded: "Pagamento a verificar",
    confirmed: "Confirmada",
    shipped: "Enviada",
    delivered: "Entregue",
    cancelled: "Cancelada",
    paid: "Paga",
    companyReg: "Registo: ",
    vatNumber: "NIF: ",
    termsTitle: "Condicoes",
    terms: "Pagamento no ato. Atrasos sujeitos a juros.",
    bankDetails: "Dados bancarios",
  },
};

function getLocale(lang: string): string {
  const locales: Record<string, string> = {
    fr: "fr-FR",
    en: "en-GB",
    de: "de-DE",
    es: "es-ES",
    it: "it-IT",
    pt: "pt-PT",
  };
  return locales[lang] || "en-GB";
}

// Custom price formatter that avoids special Unicode spaces that pdf-lib can't encode
function formatPrice(price: number, locale: string): string {
  // Format with Intl, then replace narrow no-break space (U+202F) and non-breaking space (U+00A0) with regular space
  const formatted = new Intl.NumberFormat(locale, {
    style: "currency",
    currency: "EUR",
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(price);
  
  // Replace all special spaces with regular ASCII space
  return formatted.replace(/[\u00A0\u202F\u2009\u200A]/g, " ");
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Create client with service role for data access
    const supabaseClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
    );

    // Create client with anon key for auth verification
    const authClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_ANON_KEY") ?? ""
    );

    // Verify authentication
    const authHeader = req.headers.get("Authorization");
    if (!authHeader || !authHeader.startsWith("Bearer ")) {
      console.error("Missing or invalid Authorization header");
      return new Response(
        JSON.stringify({ error: "Unauthorized" }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const token = authHeader.replace("Bearer ", "");
    const { data: { user }, error: authError } = await authClient.auth.getUser(token);
    
    if (authError || !user) {
      console.error("Auth verification failed:", authError);
      return new Response(
        JSON.stringify({ error: "Unauthorized" }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    console.log(`Invoice request by user ${user.id}`);

    const { orderId, language = "en" } = await req.json();
    const lang = translations[language] ? language : "en";
    const t = translations[lang];
    const locale = getLocale(lang);

    if (!orderId) {
      return new Response(
        JSON.stringify({ error: "Order ID is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Fetch order
    const { data: order, error: orderError } = await supabaseClient
      .from("orders")
      .select("*")
      .eq("id", orderId)
      .single();

    if (orderError || !order) {
      console.error("Order fetch error:", orderError);
      return new Response(
        JSON.stringify({ error: "Order not found" }),
        { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Check if user owns this order or is an admin
    const { data: isAdmin } = await supabaseClient.rpc("has_role", { 
      _user_id: user.id, 
      _role: "admin" 
    });

    if (order.user_id !== user.id && !isAdmin) {
      console.error(`User ${user.id} attempted to access order ${orderId} owned by ${order.user_id}`);
      return new Response(
        JSON.stringify({ error: "Forbidden" }),
        { status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    console.log(`Generating invoice for order ${orderId}`);

    // Fetch order items
    const { data: orderItems, error: itemsError } = await supabaseClient
      .from("order_items")
      .select("*")
      .eq("order_id", orderId);

    if (itemsError) {
      console.error("Order items fetch error:", itemsError);
      return new Response(
        JSON.stringify({ error: "Failed to fetch order items" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Fetch bank accounts from database
    const { data: bankAccounts } = await supabaseClient
      .from("bank_accounts")
      .select("*")
      .eq("is_active", true);

    // Generate invoice number and date
    const invoiceNumber = `INV-${new Date(order.created_at).getFullYear()}-${order.id.slice(0, 8).toUpperCase()}`;
    const invoiceDate = new Date(order.created_at).toLocaleDateString(locale);

    // Create PDF document
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([595, 842]); // A4 size in points
    const { width, height } = page.getSize();

    // Embed fonts
    const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica);

    // Colors
    const primaryColor = rgb(0.18, 0.35, 0.15);
    const accentColor = rgb(0.96, 0.62, 0.04);
    const textColor = rgb(0.2, 0.2, 0.2);
    const mutedColor = rgb(0.4, 0.4, 0.4);

    let yPos = height - 50;

    // Header - Logo
    page.drawText("Ekip", {
      x: 50,
      y: yPos,
      size: 28,
      font: helveticaBold,
      color: primaryColor,
    });
    page.drawText("Trade", {
      x: 50 + helveticaBold.widthOfTextAtSize("Ekip", 28),
      y: yPos,
      size: 28,
      font: helveticaBold,
      color: accentColor,
    });

    // Header - Invoice info (right side)
    page.drawText(t.invoice, {
      x: width - 150,
      y: yPos,
      size: 24,
      font: helveticaBold,
      color: primaryColor,
    });

    yPos -= 25;
    page.drawText(`${t.invoiceNumber} ${invoiceNumber}`, {
      x: width - 200,
      y: yPos,
      size: 10,
      font: helvetica,
      color: mutedColor,
    });

    yPos -= 15;
    page.drawText(`${t.date}: ${invoiceDate}`, {
      x: width - 200,
      y: yPos,
      size: 10,
      font: helvetica,
      color: mutedColor,
    });

    yPos -= 15;
    const statusLabel = t[order.status as keyof typeof t] || order.status;
    page.drawText(`${t.status}: ${statusLabel}`, {
      x: width - 200,
      y: yPos,
      size: 10,
      font: helvetica,
      color: mutedColor,
    });

    // Header line
    yPos -= 20;
    page.drawLine({
      start: { x: 50, y: yPos },
      end: { x: width - 50, y: yPos },
      thickness: 2,
      color: primaryColor,
    });

    // Addresses section
    yPos -= 40;

    // Seller address (UK-based company)
    page.drawText(t.seller, {
      x: 50,
      y: yPos,
      size: 10,
      font: helveticaBold,
      color: primaryColor,
    });
    yPos -= 18;
    page.drawText("EkipTrade", { x: 50, y: yPos, size: 11, font: helveticaBold, color: textColor });
    yPos -= 15;
    page.drawText(t.marketplace, { x: 50, y: yPos, size: 10, font: helvetica, color: mutedColor });
    yPos -= 15;
    page.drawText("Via Vittorio Veneto 118", { x: 50, y: yPos, size: 10, font: helvetica, color: mutedColor });
    yPos -= 15;
    page.drawText("28040 Oleggio Castello (NO), Italia", { x: 50, y: yPos, size: 10, font: helvetica, color: mutedColor });
    yPos -= 15;
    page.drawText("Tel: +39 377 389 0872", { x: 50, y: yPos, size: 10, font: helvetica, color: mutedColor });
    yPos -= 15;
    page.drawText("infos@ekip-trade.com", { x: 50, y: yPos, size: 10, font: helvetica, color: mutedColor });
    yPos -= 15;
    page.drawText(`${t.vatNumber}IT10992060011`, { x: 50, y: yPos, size: 9, font: helvetica, color: mutedColor });

    // Client address (right side)
    let clientY = yPos + 93;
    page.drawText(t.billedTo, {
      x: 320,
      y: clientY,
      size: 10,
      font: helveticaBold,
      color: primaryColor,
    });
    clientY -= 18;
    page.drawText(order.shipping_name || "N/A", { x: 320, y: clientY, size: 11, font: helveticaBold, color: textColor });
    clientY -= 15;
    if (order.shipping_address) {
      page.drawText(order.shipping_address, { x: 320, y: clientY, size: 10, font: helvetica, color: mutedColor });
      clientY -= 15;
    }
    page.drawText(`${order.shipping_postal_code || ""} ${order.shipping_city || ""}`.trim(), { x: 320, y: clientY, size: 10, font: helvetica, color: mutedColor });
    clientY -= 15;
    page.drawText(order.shipping_country || "France", { x: 320, y: clientY, size: 10, font: helvetica, color: mutedColor });
    clientY -= 15;
    if (order.shipping_email) {
      page.drawText(order.shipping_email, { x: 320, y: clientY, size: 10, font: helvetica, color: mutedColor });
      clientY -= 15;
    }
    if (order.shipping_phone) {
      page.drawText(order.shipping_phone, { x: 320, y: clientY, size: 10, font: helvetica, color: mutedColor });
    }

    // Items table
    yPos -= 50;

    // Table header
    page.drawRectangle({
      x: 50,
      y: yPos - 5,
      width: width - 100,
      height: 25,
      color: primaryColor,
    });

    // Column positions - adjusted for better spacing
    const colDesc = 55;
    const colQty = 320;
    const colUnitPrice = 370;
    const colTotal = 480;

    page.drawText(t.description, { x: colDesc, y: yPos + 3, size: 10, font: helveticaBold, color: rgb(1, 1, 1) });
    page.drawText(t.qty, { x: colQty, y: yPos + 3, size: 10, font: helveticaBold, color: rgb(1, 1, 1) });
    page.drawText(t.unitPrice, { x: colUnitPrice, y: yPos + 3, size: 10, font: helveticaBold, color: rgb(1, 1, 1) });
    page.drawText(t.total, { x: colTotal, y: yPos + 3, size: 10, font: helveticaBold, color: rgb(1, 1, 1) });

    yPos -= 25;

    // Table rows - Calculate totals from actual items
    let totalTTC = 0;
    for (let i = 0; i < (orderItems?.length || 0); i++) {
      const item = orderItems![i];
      const itemTotal = Number(item.product_price) * item.quantity;
      totalTTC += itemTotal;

      // Alternate row background
      if (i % 2 === 1) {
        page.drawRectangle({
          x: 50,
          y: yPos - 5,
          width: width - 100,
          height: 22,
          color: rgb(0.97, 0.97, 0.97),
        });
      }

      // Truncate long titles
      let title = item.product_title;
      if (title.length > 35) {
        title = title.substring(0, 32) + "...";
      }

      page.drawText(title, { x: colDesc, y: yPos + 3, size: 10, font: helvetica, color: textColor });
      page.drawText(item.quantity.toString(), { x: colQty + 10, y: yPos + 3, size: 10, font: helvetica, color: textColor });
      page.drawText(formatPrice(Number(item.product_price), locale), { x: colUnitPrice, y: yPos + 3, size: 9, font: helvetica, color: textColor });
      page.drawText(formatPrice(itemTotal, locale), { x: colTotal, y: yPos + 3, size: 9, font: helvetica, color: textColor });

      yPos -= 22;
    }

    // Separator line
    yPos -= 10;
    page.drawLine({
      start: { x: 50, y: yPos },
      end: { x: width - 50, y: yPos },
      thickness: 0.5,
      color: rgb(0.85, 0.85, 0.85),
    });

    // Totals section (right aligned) - wider spacing to avoid overlap
    yPos -= 30;
    const labelX = 350;
    const valueX = 480;

    // Calculate HT and TVA from TTC
    const htAmount = totalTTC / 1.20;
    const tvaAmount = totalTTC - htAmount;

    page.drawText(`${t.subtotalHT}:`, { x: labelX, y: yPos, size: 10, font: helvetica, color: mutedColor });
    page.drawText(formatPrice(htAmount, locale), { x: valueX, y: yPos, size: 10, font: helvetica, color: textColor });

    yPos -= 18;
    page.drawText(`${t.vat}:`, { x: labelX, y: yPos, size: 10, font: helvetica, color: mutedColor });
    page.drawText(formatPrice(tvaAmount, locale), { x: valueX, y: yPos, size: 10, font: helvetica, color: textColor });

    yPos -= 25;
    // Total TTC box
    page.drawRectangle({
      x: labelX - 10,
      y: yPos - 8,
      width: width - labelX - 30,
      height: 28,
      color: primaryColor,
    });
    page.drawText(`${t.totalTTC}:`, { x: labelX, y: yPos, size: 11, font: helveticaBold, color: rgb(1, 1, 1) });
    page.drawText(formatPrice(totalTTC, locale), { x: valueX, y: yPos, size: 11, font: helveticaBold, color: rgb(1, 1, 1) });

    // Bank info section - positioned lower on the page
    yPos -= 70;
    const bankBoxHeight = 100;
    const bankBoxY = yPos - bankBoxHeight + 15;
    
    page.drawRectangle({
      x: 50,
      y: bankBoxY,
      width: width - 100,
      height: bankBoxHeight,
      color: rgb(0.97, 0.97, 0.97),
      borderColor: rgb(0.9, 0.9, 0.9),
      borderWidth: 1,
    });

    page.drawText(t.paymentInfo, { x: 60, y: yPos - 5, size: 12, font: helveticaBold, color: primaryColor });
    page.drawText(t.paymentMethod, { x: 60, y: yPos - 25, size: 10, font: helvetica, color: mutedColor });
    
    // Get bank details from database or use defaults
    let bankDetails = { iban: "GB82 WEST 1234 5698 7654 32", bic: "WESTGB2L", holder: "EkipTrade Ltd" };
    if (bankAccounts && bankAccounts.length > 0) {
      const selectedAccount = bankAccounts.find(acc => 
        totalTTC >= (acc.threshold_min || 0) && 
        (acc.threshold_max === null || totalTTC <= acc.threshold_max)
      ) || bankAccounts[0];
      bankDetails = { iban: selectedAccount.iban, bic: selectedAccount.bic, holder: selectedAccount.holder || "EkipTrade Ltd" };
    }
    
    page.drawText(`${t.bankDetails}:`, { x: 60, y: yPos - 42, size: 10, font: helveticaBold, color: textColor });
    page.drawText(`IBAN: ${bankDetails.iban}`, { x: 60, y: yPos - 57, size: 10, font: helvetica, color: mutedColor });
    page.drawText(`BIC: ${bankDetails.bic}`, { x: 280, y: yPos - 57, size: 10, font: helvetica, color: mutedColor });
    page.drawText(`${t.reference}: ${invoiceNumber}`, { x: 60, y: yPos - 72, size: 10, font: helvetica, color: mutedColor });

    // Stamp/Signature section - positioned BELOW the payment info box
    const stampY = bankBoxY - 20; // Below the bank box
    try {
      const stampUrl = "https://ekiptrade.com/invoice-stamp.png";
      const stampResponse = await fetch(stampUrl);
      if (stampResponse.ok) {
        const stampBytes = new Uint8Array(await stampResponse.arrayBuffer());
        const stampImage = await pdfDoc.embedPng(stampBytes);
        const stampDims = stampImage.scale(0.25); // Scale the stamp
        // Position stamp at bottom-right, below the payment box
        page.drawImage(stampImage, {
          x: width - 50 - stampDims.width,
          y: stampY - stampDims.height,
          width: stampDims.width,
          height: stampDims.height,
        });
      }
    } catch (stampError) {
      console.log("Stamp image not available, skipping:", stampError);
    }

    // Footer with terms
    const footerY = 50;
    page.drawLine({
      start: { x: 50, y: footerY + 30 },
      end: { x: width - 50, y: footerY + 30 },
      thickness: 0.5,
      color: rgb(0.85, 0.85, 0.85),
    });

    page.drawText(`EkipTrade Ltd - ${t.marketplace}`, {
      x: 160,
      y: footerY + 15,
      size: 9,
      font: helvetica,
      color: mutedColor,
    });
    page.drawText(t.autoGenerated, {
      x: 130,
      y: footerY,
      size: 8,
      font: helvetica,
      color: rgb(0.6, 0.6, 0.6),
    });

    // Serialize PDF to bytes
    const pdfBytes = await pdfDoc.save();

    return new Response(new Uint8Array(pdfBytes).buffer as ArrayBuffer, {
      headers: {
        ...corsHeaders,
        "Content-Type": "application/pdf",
        "Content-Disposition": `inline; filename="invoice-${invoiceNumber}.pdf"`,
      },
    });
  } catch (error: unknown) {
    console.error("Error generating invoice:", error);
    const errorMessage = error instanceof Error ? error.message : "Unknown error";
    return new Response(
      JSON.stringify({ error: "Failed to generate invoice", details: errorMessage }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
