
-- Add avatar URL column to testimonials
ALTER TABLE public.testimonials ADD COLUMN IF NOT EXISTS author_avatar_url TEXT;

-- Delete existing testimonials to replace with comprehensive set
DELETE FROM public.testimonials;

-- Insert 22 testimonials with multilingual content and realistic avatar URLs
INSERT INTO public.testimonials (author_name, author_location, author_company, content, content_translations, rating, is_featured, is_active, author_avatar_url) VALUES
('Marco Bianchi', 'Lombardia, Italia', 'Azienda Agricola Bianchi', 'Servizio eccellente! Ho acquistato un trattore John Deere in ottime condizioni. La consegna è stata rapida e il team molto professionale.', '{"it":"Servizio eccellente! Ho acquistato un trattore John Deere in ottime condizioni. La consegna è stata rapida e il team molto professionale.","fr":"Service excellent ! J''ai acheté un tracteur John Deere en très bon état. La livraison a été rapide et l''équipe très professionnelle.","en":"Excellent service! I purchased a John Deere tractor in great condition. Delivery was fast and the team very professional.","de":"Ausgezeichneter Service! Ich habe einen John Deere Traktor in hervorragendem Zustand gekauft. Die Lieferung war schnell und das Team sehr professionell.","es":"¡Servicio excelente! Compré un tractor John Deere en muy buen estado. La entrega fue rápida y el equipo muy profesional.","pt":"Serviço excelente! Comprei um trator John Deere em ótimas condições. A entrega foi rápida e a equipe muito profissional."}', 5, true, true, 'https://randomuser.me/api/portraits/men/32.jpg'),

('Sophie Müller', 'Bayern, Deutschland', 'Müller Landtechnik', 'Fantastische Auswahl an Landmaschinen. Die Preise sind fair und die Qualität der Maschinen übertrifft meine Erwartungen. Sehr empfehlenswert!', '{"it":"Fantastica selezione di macchine agricole. I prezzi sono giusti e la qualità delle macchine supera le mie aspettative. Molto raccomandato!","fr":"Fantastique sélection de machines agricoles. Les prix sont justes et la qualité des machines dépasse mes attentes. Très recommandé !","en":"Fantastic selection of agricultural machinery. Prices are fair and the quality of machines exceeds my expectations. Highly recommended!","de":"Fantastische Auswahl an Landmaschinen. Die Preise sind fair und die Qualität der Maschinen übertrifft meine Erwartungen. Sehr empfehlenswert!","es":"¡Fantástica selección de maquinaria agrícola! Los precios son justos y la calidad de las máquinas supera mis expectativas. ¡Muy recomendable!","pt":"Fantástica seleção de máquinas agrícolas. Os preços são justos e a qualidade das máquinas supera minhas expectativas. Muito recomendável!"}', 5, true, true, 'https://randomuser.me/api/portraits/women/44.jpg'),

('Jean-Pierre Duval', 'Bretagne, France', 'GAEC Duval & Fils', 'Je suis client depuis 2 ans et je n''ai jamais été déçu. Les pièces détachées sont toujours disponibles et le service après-vente est irréprochable.', '{"it":"Sono cliente da 2 anni e non sono mai stato deluso. I ricambi sono sempre disponibili e il servizio post-vendita è impeccabile.","fr":"Je suis client depuis 2 ans et je n''ai jamais été déçu. Les pièces détachées sont toujours disponibles et le service après-vente est irréprochable.","en":"I have been a customer for 2 years and have never been disappointed. Spare parts are always available and after-sales service is impeccable.","de":"Ich bin seit 2 Jahren Kunde und wurde nie enttäuscht. Ersatzteile sind immer verfügbar und der Kundendienst ist tadellos.","es":"Soy cliente desde hace 2 años y nunca me han decepcionado. Los repuestos siempre están disponibles y el servicio postventa es impecable.","pt":"Sou cliente há 2 anos e nunca fiquei desapontado. As peças de reposição estão sempre disponíveis e o serviço pós-venda é impecável."}', 5, true, true, 'https://randomuser.me/api/portraits/men/45.jpg'),

('Carlos Rodriguez', 'Andalucía, España', 'Agrícola Rodriguez S.L.', 'Compré una cosechadora Claas y estoy muy satisfecho. El equipo me ayudó a elegir el modelo perfecto para mis necesidades.', '{"it":"Ho comprato una mietitrebbia Claas e sono molto soddisfatto. Il team mi ha aiutato a scegliere il modello perfetto per le mie esigenze.","fr":"J''ai acheté une moissonneuse Claas et je suis très satisfait. L''équipe m''a aidé à choisir le modèle parfait pour mes besoins.","en":"I bought a Claas harvester and I am very satisfied. The team helped me choose the perfect model for my needs.","de":"Ich habe einen Claas Mähdrescher gekauft und bin sehr zufrieden. Das Team hat mir geholfen, das perfekte Modell für meine Bedürfnisse zu wählen.","es":"Compré una cosechadora Claas y estoy muy satisfecho. El equipo me ayudó a elegir el modelo perfecto para mis necesidades.","pt":"Comprei uma colheitadeira Claas e estou muito satisfeito. A equipe me ajudou a escolher o modelo perfeito para minhas necessidades."}', 5, true, true, 'https://randomuser.me/api/portraits/men/52.jpg'),

('Maria Santos', 'Alentejo, Portugal', 'Quinta dos Santos', 'Ótima experiência de compra! O processo foi simples e transparente. Recebi o meu trator New Holland em perfeitas condições.', '{"it":"Ottima esperienza di acquisto! Il processo è stato semplice e trasparente. Ho ricevuto il mio trattore New Holland in perfette condizioni.","fr":"Excellente expérience d''achat ! Le processus a été simple et transparent. J''ai reçu mon tracteur New Holland en parfait état.","en":"Great buying experience! The process was simple and transparent. I received my New Holland tractor in perfect condition.","de":"Tolle Kauferfahrung! Der Prozess war einfach und transparent. Ich habe meinen New Holland Traktor in perfektem Zustand erhalten.","es":"¡Gran experiencia de compra! El proceso fue simple y transparente. Recibí mi tractor New Holland en perfectas condiciones.","pt":"Ótima experiência de compra! O processo foi simples e transparente. Recebi o meu trator New Holland em perfeitas condições."}', 5, true, true, 'https://randomuser.me/api/portraits/women/65.jpg'),

('Giovanni Rossi', 'Toscana, Italia', 'Rossi Agricoltura', 'Prezzi competitivi e macchinari di alta qualità. Ho trovato esattamente quello che cercavo per la mia azienda agricola.', '{"it":"Prezzi competitivi e macchinari di alta qualità. Ho trovato esattamente quello che cercavo per la mia azienda agricola.","fr":"Prix compétitifs et machines de haute qualité. J''ai trouvé exactement ce que je cherchais pour mon exploitation agricole.","en":"Competitive prices and high-quality machinery. I found exactly what I was looking for for my farm.","de":"Wettbewerbsfähige Preise und hochwertige Maschinen. Ich habe genau das gefunden, was ich für meinen Bauernhof gesucht habe.","es":"Precios competitivos y maquinaria de alta calidad. Encontré exactamente lo que buscaba para mi granja.","pt":"Preços competitivos e máquinas de alta qualidade. Encontrei exatamente o que procurava para a minha fazenda."}', 5, true, true, 'https://randomuser.me/api/portraits/men/67.jpg'),

('Anna Schneider', 'Niedersachsen, Deutschland', 'Schneider Hof', 'Der Kundenservice ist erstklassig. Bei Fragen wurde mir immer schnell und kompetent geholfen. Ich kaufe hier gerne wieder ein.', '{"it":"Il servizio clienti è di prima classe. Le mie domande hanno sempre ricevuto risposte rapide e competenti. Comprerò di nuovo qui con piacere.","fr":"Le service client est de première classe. Mes questions ont toujours reçu des réponses rapides et compétentes. J''achèterai à nouveau ici avec plaisir.","en":"Customer service is first class. My questions were always answered quickly and competently. I will gladly shop here again.","de":"Der Kundenservice ist erstklassig. Bei Fragen wurde mir immer schnell und kompetent geholfen. Ich kaufe hier gerne wieder ein.","es":"El servicio al cliente es de primera clase. Mis preguntas siempre fueron respondidas de forma rápida y competente. Compraré aquí de nuevo con gusto.","pt":"O atendimento ao cliente é de primeira classe. Minhas perguntas sempre foram respondidas de forma rápida e competente. Comprarei aqui novamente com prazer."}', 4, true, true, 'https://randomuser.me/api/portraits/women/33.jpg'),

('Pierre Lambert', 'Normandie, France', 'EARL Lambert', 'Très bon rapport qualité-prix. Le matériel d''occasion est soigneusement vérifié avant la vente. Je recommande vivement cette plateforme.', '{"it":"Ottimo rapporto qualità-prezzo. L''attrezzatura usata viene accuratamente verificata prima della vendita. Raccomando vivamente questa piattaforma.","fr":"Très bon rapport qualité-prix. Le matériel d''occasion est soigneusement vérifié avant la vente. Je recommande vivement cette plateforme.","en":"Very good value for money. Used equipment is carefully checked before sale. I highly recommend this platform.","de":"Sehr gutes Preis-Leistungs-Verhältnis. Gebrauchte Geräte werden vor dem Verkauf sorgfältig geprüft. Ich empfehle diese Plattform sehr.","es":"Muy buena relación calidad-precio. El equipo usado se verifica cuidadosamente antes de la venta. Recomiendo encarecidamente esta plataforma.","pt":"Muito boa relação qualidade-preço. O equipamento usado é cuidadosamente verificado antes da venda. Recomendo vivamente esta plataforma."}', 5, true, true, 'https://randomuser.me/api/portraits/men/22.jpg'),

('Elena Fernández', 'Castilla y León, España', 'Fernández Agro', 'Encontré una excelente oferta en un tractor Fendt. Todo el proceso de compra fue profesional y sin complicaciones.', '{"it":"Ho trovato un''ottima offerta su un trattore Fendt. Tutto il processo di acquisto è stato professionale e senza complicazioni.","fr":"J''ai trouvé une excellente offre sur un tracteur Fendt. Tout le processus d''achat a été professionnel et sans complications.","en":"I found an excellent deal on a Fendt tractor. The entire purchase process was professional and hassle-free.","de":"Ich habe ein ausgezeichnetes Angebot für einen Fendt Traktor gefunden. Der gesamte Kaufprozess war professionell und unkompliziert.","es":"Encontré una excelente oferta en un tractor Fendt. Todo el proceso de compra fue profesional y sin complicaciones.","pt":"Encontrei uma excelente oferta num trator Fendt. Todo o processo de compra foi profissional e sem complicações."}', 5, true, true, 'https://randomuser.me/api/portraits/women/28.jpg'),

('Thomas Weber', 'Steiermark, Österreich', 'Weber Agrartechnik', 'Schnelle Lieferung und perfekter Zustand der Maschine. Die Kommunikation war transparent und zuverlässig.', '{"it":"Consegna rapida e macchina in perfette condizioni. La comunicazione è stata trasparente e affidabile.","fr":"Livraison rapide et machine en parfait état. La communication a été transparente et fiable.","en":"Fast delivery and perfect condition of the machine. Communication was transparent and reliable.","de":"Schnelle Lieferung und perfekter Zustand der Maschine. Die Kommunikation war transparent und zuverlässig.","es":"Entrega rápida y máquina en perfecto estado. La comunicación fue transparente y confiable.","pt":"Entrega rápida e máquina em perfeito estado. A comunicação foi transparente e confiável."}', 5, true, true, 'https://randomuser.me/api/portraits/men/41.jpg'),

('Lucia Conti', 'Emilia-Romagna, Italia', 'Conti Vigneti', 'Ho acquistato attrezzatura per la viticoltura. Ottima consulenza e tempi di consegna rispettati. Tornerò sicuramente!', '{"it":"Ho acquistato attrezzatura per la viticoltura. Ottima consulenza e tempi di consegna rispettati. Tornerò sicuramente!","fr":"J''ai acheté du matériel viticole. Excellent conseil et délais de livraison respectés. Je reviendrai certainement !","en":"I purchased viticulture equipment. Excellent advice and delivery times met. I will definitely come back!","de":"Ich habe Weinbauausrüstung gekauft. Hervorragende Beratung und Lieferzeiten eingehalten. Ich komme definitiv wieder!","es":"Compré equipos de viticultura. Excelente asesoramiento y plazos de entrega cumplidos. ¡Volveré seguro!","pt":"Comprei equipamento de viticultura. Excelente aconselhamento e prazos de entrega cumpridos. Voltarei com certeza!"}', 5, true, true, 'https://randomuser.me/api/portraits/women/52.jpg'),

('François Martin', 'Champagne, France', 'SCEA Martin', 'La plateforme est très intuitive. J''ai pu comparer facilement les différents modèles et trouver la meilleure offre pour mon exploitation.', '{"it":"La piattaforma è molto intuitiva. Ho potuto confrontare facilmente i diversi modelli e trovare la migliore offerta per la mia azienda.","fr":"La plateforme est très intuitive. J''ai pu comparer facilement les différents modèles et trouver la meilleure offre pour mon exploitation.","en":"The platform is very intuitive. I was able to easily compare different models and find the best deal for my farm.","de":"Die Plattform ist sehr intuitiv. Ich konnte verschiedene Modelle einfach vergleichen und das beste Angebot für meinen Betrieb finden.","es":"La plataforma es muy intuitiva. Pude comparar fácilmente los diferentes modelos y encontrar la mejor oferta para mi explotación.","pt":"A plataforma é muito intuitiva. Pude comparar facilmente os diferentes modelos e encontrar a melhor oferta para a minha exploração."}', 4, true, true, 'https://randomuser.me/api/portraits/men/55.jpg'),

('Hans Braun', 'Sachsen, Deutschland', 'Braun Agrar GmbH', 'Professionelle Abwicklung von Anfang bis Ende. Die Maschinen sind genau wie beschrieben. Sehr vertrauenswürdig!', '{"it":"Gestione professionale dall''inizio alla fine. Le macchine sono esattamente come descritte. Molto affidabile!","fr":"Gestion professionnelle du début à la fin. Les machines sont exactement comme décrites. Très fiable !","en":"Professional handling from start to finish. The machines are exactly as described. Very trustworthy!","de":"Professionelle Abwicklung von Anfang bis Ende. Die Maschinen sind genau wie beschrieben. Sehr vertrauenswürdig!","es":"Gestión profesional de principio a fin. Las máquinas son exactamente como se describen. ¡Muy confiable!","pt":"Gestão profissional do início ao fim. As máquinas são exatamente como descritas. Muito confiável!"}', 5, true, true, 'https://randomuser.me/api/portraits/men/36.jpg'),

('Isabella Romano', 'Sicilia, Italia', 'Romano Agrumi', 'Eccellente piattaforma per trovare macchinari agricoli a prezzi ragionevoli. Il supporto clienti è sempre disponibile e cortese.', '{"it":"Eccellente piattaforma per trovare macchinari agricoli a prezzi ragionevoli. Il supporto clienti è sempre disponibile e cortese.","fr":"Excellente plateforme pour trouver des machines agricoles à des prix raisonnables. Le support client est toujours disponible et courtois.","en":"Excellent platform for finding agricultural machinery at reasonable prices. Customer support is always available and courteous.","de":"Hervorragende Plattform, um Landmaschinen zu vernünftigen Preisen zu finden. Der Kundensupport ist immer erreichbar und zuvorkommend.","es":"Excelente plataforma para encontrar maquinaria agrícola a precios razonables. El soporte al cliente siempre está disponible y es cortés.","pt":"Excelente plataforma para encontrar máquinas agrícolas a preços razoáveis. O suporte ao cliente está sempre disponível e é cortês."}', 5, true, true, 'https://randomuser.me/api/portraits/women/42.jpg'),

('Miguel Oliveira', 'Trás-os-Montes, Portugal', 'Oliveira & Filhos', 'Comprei um trator Massey Ferguson e fiquei muito impressionado com o estado da máquina. Excelente negócio!', '{"it":"Ho comprato un trattore Massey Ferguson e sono rimasto molto impressionato dallo stato della macchina. Ottimo affare!","fr":"J''ai acheté un tracteur Massey Ferguson et j''ai été très impressionné par l''état de la machine. Excellente affaire !","en":"I bought a Massey Ferguson tractor and was very impressed with the condition of the machine. Excellent deal!","de":"Ich habe einen Massey Ferguson Traktor gekauft und war sehr beeindruckt vom Zustand der Maschine. Ausgezeichnetes Geschäft!","es":"Compré un tractor Massey Ferguson y quedé muy impresionado con el estado de la máquina. ¡Excelente negocio!","pt":"Comprei um trator Massey Ferguson e fiquei muito impressionado com o estado da máquina. Excelente negócio!"}', 5, true, true, 'https://randomuser.me/api/portraits/men/48.jpg'),

('Christine Dubois', 'Bourgogne, France', 'Domaine Dubois', 'Un grand choix de matériel viticole et agricole. Les photos et descriptions sont précises, ce qui facilite le choix.', '{"it":"Una grande scelta di attrezzature viticole e agricole. Le foto e le descrizioni sono precise, facilitando la scelta.","fr":"Un grand choix de matériel viticole et agricole. Les photos et descriptions sont précises, ce qui facilite le choix.","en":"A great selection of viticultural and agricultural equipment. Photos and descriptions are accurate, making it easy to choose.","de":"Eine große Auswahl an Wein- und Landwirtschaftsgeräten. Fotos und Beschreibungen sind genau, was die Auswahl erleichtert.","es":"Una gran selección de equipos vitícolas y agrícolas. Las fotos y descripciones son precisas, lo que facilita la elección.","pt":"Uma grande seleção de equipamentos vitícolas e agrícolas. As fotos e descrições são precisas, facilitando a escolha."}', 4, true, true, 'https://randomuser.me/api/portraits/women/56.jpg'),

('Roberto Ferretti', 'Veneto, Italia', 'Ferretti Cereali', 'Acquisto dopo acquisto, sempre soddisfatto. La qualità del servizio è costante e i prezzi sono sempre competitivi.', '{"it":"Acquisto dopo acquisto, sempre soddisfatto. La qualità del servizio è costante e i prezzi sono sempre competitivi.","fr":"Achat après achat, toujours satisfait. La qualité du service est constante et les prix sont toujours compétitifs.","en":"Purchase after purchase, always satisfied. Service quality is consistent and prices are always competitive.","de":"Kauf für Kauf, immer zufrieden. Die Servicequalität ist konstant und die Preise sind immer wettbewerbsfähig.","es":"Compra tras compra, siempre satisfecho. La calidad del servicio es constante y los precios siempre son competitivos.","pt":"Compra após compra, sempre satisfeito. A qualidade do serviço é constante e os preços são sempre competitivos."}', 5, true, true, 'https://randomuser.me/api/portraits/men/61.jpg'),

('Klaus Fischer', 'Baden-Württemberg, Deutschland', 'Fischer Landwirtschaft', 'Hervorragende Beratung bei der Auswahl meines neuen Mähdreschers. Das Team kennt sich wirklich mit Landmaschinen aus.', '{"it":"Eccellente consulenza nella scelta della mia nuova mietitrebbia. Il team conosce davvero le macchine agricole.","fr":"Excellent conseil pour le choix de ma nouvelle moissonneuse-batteuse. L''équipe connaît vraiment les machines agricoles.","en":"Excellent advice when choosing my new combine harvester. The team really knows about agricultural machinery.","de":"Hervorragende Beratung bei der Auswahl meines neuen Mähdreschers. Das Team kennt sich wirklich mit Landmaschinen aus.","es":"Excelente asesoramiento al elegir mi nueva cosechadora. El equipo realmente conoce la maquinaria agrícola.","pt":"Excelente aconselhamento na escolha da minha nova colheitadeira. A equipe realmente entende de máquinas agrícolas."}', 5, true, true, 'https://randomuser.me/api/portraits/men/29.jpg'),

('Paola Greco', 'Puglia, Italia', 'Oleificio Greco', 'Piattaforma seria e affidabile. Ho trovato l''attrezzatura per il mio frantoio a un prezzo imbattibile. Grazie Ekip Trade!', '{"it":"Piattaforma seria e affidabile. Ho trovato l''attrezzatura per il mio frantoio a un prezzo imbattibile. Grazie Ekip Trade!","fr":"Plateforme sérieuse et fiable. J''ai trouvé l''équipement pour mon pressoir à un prix imbattable. Merci Ekip Trade !","en":"Serious and reliable platform. I found the equipment for my olive press at an unbeatable price. Thank you Ekip Trade!","de":"Seriöse und zuverlässige Plattform. Ich habe die Ausrüstung für meine Ölmühle zu einem unschlagbaren Preis gefunden. Danke Ekip Trade!","es":"Plataforma seria y confiable. Encontré el equipo para mi almazara a un precio inmejorable. ¡Gracias Ekip Trade!","pt":"Plataforma séria e confiável. Encontrei o equipamento para o meu lagar a um preço imbatível. Obrigado Ekip Trade!"}', 5, true, true, 'https://randomuser.me/api/portraits/women/39.jpg'),

('James O''Brien', 'Cork, Ireland', 'O''Brien Farming', 'Brilliant service from start to finish. Found a Kubota tractor at a great price. International shipping was smooth and well-organized.', '{"it":"Servizio brillante dall''inizio alla fine. Ho trovato un trattore Kubota a un ottimo prezzo. La spedizione internazionale è stata fluida e ben organizzata.","fr":"Service brillant du début à la fin. J''ai trouvé un tracteur Kubota à un excellent prix. L''expédition internationale a été fluide et bien organisée.","en":"Brilliant service from start to finish. Found a Kubota tractor at a great price. International shipping was smooth and well-organized.","de":"Brillanter Service von Anfang bis Ende. Habe einen Kubota Traktor zu einem tollen Preis gefunden. Der internationale Versand war reibungslos und gut organisiert.","es":"Servicio brillante de principio a fin. Encontré un tractor Kubota a un gran precio. El envío internacional fue fluido y bien organizado.","pt":"Serviço brilhante do início ao fim. Encontrei um trator Kubota a um ótimo preço. O envio internacional foi tranquilo e bem organizado."}', 5, true, true, 'https://randomuser.me/api/portraits/men/75.jpg'),

('Alessandra Martini', 'Piemonte, Italia', 'Cantina Martini', 'Ottimo servizio di assistenza post-vendita. Quando ho avuto un problema con la consegna, è stato risolto immediatamente. Professionalità al top!', '{"it":"Ottimo servizio di assistenza post-vendita. Quando ho avuto un problema con la consegna, è stato risolto immediatamente. Professionalità al top!","fr":"Excellent service après-vente. Quand j''ai eu un problème avec la livraison, il a été résolu immédiatement. Professionnalisme au top !","en":"Excellent after-sales service. When I had a delivery issue, it was resolved immediately. Top professionalism!","de":"Ausgezeichneter Kundendienst. Als ich ein Problem mit der Lieferung hatte, wurde es sofort gelöst. Top Professionalität!","es":"Excelente servicio postventa. Cuando tuve un problema con la entrega, se resolvió de inmediato. ¡Profesionalismo de primera!","pt":"Excelente serviço pós-venda. Quando tive um problema com a entrega, foi resolvido imediatamente. Profissionalismo de topo!"}', 5, true, true, 'https://randomuser.me/api/portraits/women/47.jpg'),

('André Lefèvre', 'Provence, France', 'Mas Lefèvre', 'Deuxième achat sur la plateforme et toujours aussi satisfait. Un large choix de matériel agricole de qualité à des prix raisonnables.', '{"it":"Secondo acquisto sulla piattaforma e sempre soddisfatto. Un''ampia scelta di attrezzature agricole di qualità a prezzi ragionevoli.","fr":"Deuxième achat sur la plateforme et toujours aussi satisfait. Un large choix de matériel agricole de qualité à des prix raisonnables.","en":"Second purchase on the platform and still very satisfied. A wide choice of quality agricultural equipment at reasonable prices.","de":"Zweiter Kauf auf der Plattform und immer noch sehr zufrieden. Eine große Auswahl an hochwertigen Landmaschinen zu vernünftigen Preisen.","es":"Segunda compra en la plataforma y sigo muy satisfecho. Una amplia selección de equipos agrícolas de calidad a precios razonables.","pt":"Segunda compra na plataforma e continuo muito satisfeito. Uma grande seleção de equipamentos agrícolas de qualidade a preços razoáveis."}', 4, true, true, 'https://randomuser.me/api/portraits/men/64.jpg');
